### ISSUE TITLE
What is a default pass-through Transformation in UnboundedFlinkSource?

### ISSUE THREAD

**Issue by amirtousa** [dataArtisans/flink-dataflow#24]
Hello,
I am trying to execute a statement like this:
 PCollection<String> lines = p
				  .apply(Read.named("StreamingMyData").from(UnboundedFlinkSource.of(kafkaConsumer))).apply(Window.<String>into(FixedWindows.of(Duration.standardSeconds(5)))
		            .triggering(AfterWatermark.pastEndOfWindow()).withAllowedLateness(Duration.ZERO)
		            .discardingFiredPanes());
But I really don't want to transform/alter the incoming data. I just want to print or use it "as is" coming from Kafka.
How can I bypass the need for a transform like ("StreamingMyData") and just print the data as its coming in from Kafka?
Thanks so much for your help.

**Comment by aljoscha** [comment]
Hi Amir,
this repository and code has been superseded by Apache Beam, which now also includes the Flink runner: http://beam.incubator.apache.org

Please use the mailing lists there if you have any questions: http://beam.incubator.apache.org/mailing_lists/
