### ISSUE TITLE
FlinkRunnerResult.getState always returns null?

### ISSUE THREAD

**Issue by xfeep** [dataArtisans/flink-dataflow#25]
In https://github.com/dataArtisans/flink-dataflow/blob/master/runner/src/main/java/com/dataartisans/flink/dataflow/FlinkRunnerResult.java#L47 

``` java
    @Override
    public State getState() {
        return null;
    }
```

How can we monitor the process of a job? Thanks.

**Comment by aljoscha** [comment]
Hi,
this repository is outdated. Please check out http://beam.incubator.apache.org. This is the apache licensed open-source API of Google Dataflow that also contains an updated Flink runner.

**Comment by mxm** [comment]
Thanks for your question. Please check out the up to date version of the code in the Beam repository: http://beam.incubator.apache.org/

Report any BEAM related bugs to https://issues.apache.org/jira/browse/BEAM/
