### ISSUE TITLE
Flink-Dataflow with custom sources

### ISSUE THREAD

**Issue by fsalem** [dataArtisans/flink-dataflow#3]
I was trying to run a program working using Google Dataflow but with FlinkPipelineRunner. I use custom sources and Sinks to read and write data. It throws an exception saying "java.lang.UnsupportedOperationException: The transform Window.Into() is currently not supported."

Do you support custom sources/sinks or not yet ?

**Comment by rmetzger** [comment]
Hi,
thank you for looking into the flink-dataflow integration. The main author of the code is currently on vacation. He'll be back next Monday. He'll then get back to you regarding the issue.

Are you trying to use flink-dataflow for batch or stream processing?

**Comment by fsalem** [comment]
Thanks for your reply. I use Batch processing till now because ,as far as I know, stream processing is not released yet.

**Comment by mxm** [comment]
Hi @fsalem! Thanks for reporting. Could you please provide the entire stack trace?

Stream processing support will be released very soon.

**Comment by datalorax** [comment]
Likewise, would like to be able to use custom sources & sinks, e.g. Kafka.  Currently, with no way of adding a TransformTranslator, this doesn't seem to be possible.

Excited to hear stream processing support is coming soon - are you able to give any more details? Are we walking weeks or months?

**Comment by mxm** [comment]
Great to hear about your excitement :) Custom `TransformTranslator`s might be possible in the future. The upcoming streaming release will allow you to use the builtin Flink sources. It will support Dataflow's windowing semantics, allowing you to leverage the APIs power on top of Flink. Expect it soon, within the next weeks.

**Comment by datalorax** [comment]
Good stuff! 

Would it be possible to open this up to extension by adding a static method to add to the static map within FlinkStreamingTransformTranslators, e.g. a registerTranslator method?

**Comment by mxm** [comment]
I'm a bit skeptical about such a hook. I would rather provide the correct translators or interfaces out of the box. Could we move this into a separate issue? If it is just for the missing generic sink translator, we will add one such that users can implement sinks with the `Sink` interface.

**Comment by mxm** [comment]
@fsalem I've pushed a fix for the custom sinks in the master: 935843a5e372eeaed99b3e04d61fb8528990c09a. Please see if your code works now.

**Comment by fsalem** [comment]
@mxm Thanks so much. I will check it again and get back to you. Sorry for being late

**Comment by datalorax** [comment]
@mxm my request is actually on the streaming side - being able to add custom sources & sinks, or indeed leverage Flink's own Kafka source / sinks.  Sounds like its covered by your up-coming streaming release.

If you're able, it would be great if you could update the streaming version on Github, to allow me to start prototype.  Totally understand if this is not currently feasible.

**Comment by mxm** [comment]
@datalorax The patch was for the batch side. Likewise, the streaming will support custom sources/sinks. @kl0u is currently working on the streaming support. His changes are in the `streaming_new` branch but it is currently work in progress.

**Comment by mxm** [comment]
Closing this for now but feel free to reopen if you have any difficulties.
